version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: productos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - nest-net

  api:
    build:
      context: .
    container_name: nestjs_api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - nest-net

networks:
  nest-net:
